[package]
name = "catcard-ui"
description = "Display framebuffer and panel command sets for CatCard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
catcard-board.workspace = true
catcard-entropy = { workspace = true, default-features = false }
