[package]
name = "catcard-image"
description = "Build, sign, verify and package CatCard firmware images"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "catcard-image"
path = "src/main.rs"

[dependencies]
anyd.workspace = true
catcard-board.workspace = true
catcard-bbqr.workspace = true
outscript.workspace = true
catcard-fwhdr = { workspace = true, features = ["std"] }
anyhow.workspace = true
clap.workspace = true
hex.workspace = true
purecrypto = { workspace = true, features = ["hash", "ec", "hazmat-secp256k1", "bip340", "key", "der", "x509", "std"] }
