//! Generates `memory.x` for the selected board.
//!
//! The layout is not ours to choose: the bootloader installs our image at a fixed
//! address and expects the signed header at a fixed offset inside it. Deriving the
//! linker script from `catcard-board` rather than checking in three hand-written
//! copies means the board table is the single source of truth, and the
//! `firmware_base` used by the linker cannot drift from the one `catcard-image` uses
//! to flatten the ELF.

use std::env;
use std::fs;
use std::path::PathBuf;

// The board table is const data with no MCU dependencies, so the build script can use
// exactly the same definitions the firmware will.
use catcard_board::memory::{FW_HEADER_OFFSET, FW_HEADER_SIZE};

fn main() {
    let board = board_from_features();

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is always set"));
    let m = &board.memory;

    // `.text` starts after the header block. Everything from the vector table up to
    // 0x4000 is left to the fill byte, and `catcard-image` writes the 128-byte header
    // into the gap at FW_HEADER_OFFSET after linking.
    let text_offset = FW_HEADER_OFFSET + FW_HEADER_SIZE;

    let script = format!(
        "/* Generated by catcard-fw/build.rs for board \"{name}\" -- do not edit. */\n\
         \n\
         MEMORY\n\
         {{\n\
         \x20 /* Installed firmware region. Below {base:#X} is the bootloader, which is\n\
         \x20    protected flash and unreplaceable at RDP=2. */\n\
         \x20 FLASH : ORIGIN = {base:#X}, LENGTH = {flash}\n\
         \n\
         \x20 /* SRAM1 only. The bootloader callgate requires its I/O buffer to be in\n\
         \x20    SRAM1, and the sizes of SRAM2/SRAM3 are still unconfirmed. */\n\
         \x20 RAM   : ORIGIN = {ram:#X}, LENGTH = {ram_len}\n\
         }}\n\
         \n\
         /* The signed firmware header occupies {hdr_size} bytes at {hdr_off:#X} within the\n\
         \x20  image, so code starts after it. cortex-m-rt honours _stext. */\n\
         _stext = ORIGIN(FLASH) + {text_offset:#X};\n\
         \n\
         /* Reserved by the bootloader; never link anything here. */\n\
         _bootloader_sram_start = {bl_base:#X};\n\
         _bootloader_sram_end   = {bl_end:#X};\n",
        name = board.name,
        base = m.firmware_base,
        flash = m.firmware_flash_len,
        ram = m.sram1_base,
        ram_len = m.sram1_len,
        hdr_size = FW_HEADER_SIZE,
        hdr_off = FW_HEADER_OFFSET,
        text_offset = text_offset,
        bl_base = m.bl_sram_base,
        bl_end = m.bl_sram_base + m.bl_sram_len,
    );

    fs::write(out.join("memory.x"), script).expect("writing memory.x");
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-env=CATCARD_BOARD={}", board.name);
}

fn board_from_features() -> &'static catcard_board::BoardSpec {
    let mk3 = env::var_os("CARGO_FEATURE_BOARD_MK3").is_some();
    let mk4 = env::var_os("CARGO_FEATURE_BOARD_MK4").is_some();
    let q1 = env::var_os("CARGO_FEATURE_BOARD_Q1").is_some();

    match (mk3, mk4, q1) {
        (true, false, false) => &catcard_board::spec::MK3,
        (false, true, false) => &catcard_board::spec::MK4,
        (false, false, true) => &catcard_board::spec::Q1,
        (false, false, false) => panic!(
            "no board selected. Build with one of:\n  \
             cargo fw-mk3\n  cargo fw-mk4\n  cargo fw-q1"
        ),
        _ => panic!("more than one board feature is enabled; pick exactly one"),
    }
}
