//! Generates `memory.x` for the selected board.
//!
//! The layout is not ours to choose: the bootloader installs our image at a fixed
//! address and expects the signed header at a fixed offset inside it. Deriving the
//! linker script from `catcard-board` rather than checking in three hand-written
//! copies means the board table is the single source of truth, and the
//! `firmware_base` used by the linker cannot drift from the one `catcard-image` uses
//! to flatten the ELF.

use std::env;
use std::fs;
use std::path::PathBuf;

// The board table is const data with no MCU dependencies, so the build script can use
// exactly the same definitions the firmware will.
use catcard_board::memory::{FW_HEADER_OFFSET, FW_HEADER_SIZE};

fn main() {
    let board = board_from_features();

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is always set"));
    let m = &board.memory;

    // `.text` starts after the header block. Everything from the vector table up to
    // 0x4000 is left to the fill byte, and `catcard-image` writes the 128-byte header
    // into the gap at FW_HEADER_OFFSET after linking.
    let text_offset = FW_HEADER_OFFSET + FW_HEADER_SIZE;

    let script = format!(
        "/* Generated by catcard-fw/build.rs for board \"{name}\" -- do not edit. */\n\
         \n\
         MEMORY\n\
         {{\n\
         \x20 /* Installed firmware region. Below {base:#X} is the bootloader, which is\n\
         \x20    protected flash and unreplaceable at RDP=2. The length stops short of\n\
         \x20    the settings volume where the board keeps one in internal flash. */\n\
         \x20 FLASH : ORIGIN = {base:#X}, LENGTH = {flash}\n\
         \n\
         \x20 /* SRAM1 only. The bootloader callgate requires its I/O buffer to be in\n\
         \x20    SRAM1, and the sizes of SRAM2/SRAM3 are still unconfirmed. */\n\
         \x20 RAM   : ORIGIN = {ram:#X}, LENGTH = {ram_len}\n\
         }}\n\
         \n\
         /* The signed firmware header occupies {hdr_size} bytes at {hdr_off:#X} within the\n\
         \x20  image, so code starts after it. cortex-m-rt honours _stext. */\n\
         _stext = ORIGIN(FLASH) + {text_offset:#X};\n\
         \n\
         /* Reserved by the bootloader; never link anything here. */\n\
         _bootloader_sram_start = {bl_base:#X};\n\
         _bootloader_sram_end   = {bl_end:#X};\n",
        name = board.name,
        base = m.firmware_base,
        flash = board.image_ceiling(),
        ram = m.sram1_base,
        ram_len = m.sram1_len,
        hdr_size = FW_HEADER_SIZE,
        hdr_off = FW_HEADER_OFFSET,
        text_offset = text_offset,
        bl_base = m.bl_sram_base,
        bl_end = m.bl_sram_base + m.bl_sram_len,
    );

    fs::write(out.join("memory.x"), script).expect("writing memory.x");

    // Pin the callgate bounce buffer to the very base of SRAM1.
    //
    // The bootloader callgate only accepts an I/O buffer inside a window at the bottom of
    // SRAM1 -- on the mk3 that window is just the first 96 KB (`0x2000_0000`..`0x2001_8000`),
    // and a buffer above it is refused with nothing written, which reads as a login that
    // never works. Source: hw-reference/bootloader-callgate-abi.md §0.1 [C].
    //
    // `GATE_BUF` (catcard-callgate) is tagged `.gate_buf`; this fragment makes that section
    // the first thing in RAM, so the buffer sits at `ORIGIN(RAM)` on every board regardless
    // of how far `.bss` grows above it. `(NOLOAD)` because the buffer is written before every
    // read and never relies on its power-on contents, so it carries no bytes in the image.
    let gate_buf = "/* Generated by catcard-fw/build.rs -- do not edit. */\n\
         SECTIONS\n\
         {\n\
         \x20 .gate_buf (NOLOAD) : ALIGN(8)\n\
         \x20 {\n\
         \x20   KEEP(*(.gate_buf));\n\
         \x20   . = ALIGN(8);\n\
         \x20 } > RAM\n\
         } INSERT BEFORE .data;\n";
    fs::write(out.join("gate-buf.x"), gate_buf).expect("writing gate-buf.x");

    println!("cargo:rustc-link-search={}", out.display());

    // Emitted here rather than in `.cargo/config.toml`, because setting the RUSTFLAGS
    // environment variable makes cargo ignore that file's `rustflags` completely. When
    // that happened the firmware still linked -- against lld's default layout, at
    // 0x00020000 instead of the board's firmware base -- and only failed later, when
    // `catcard-image` refused to flatten it. `cargo:rustc-link-arg` is not overridable,
    // so the linker script cannot go missing.
    println!("cargo:rustc-link-arg=-Tlink.x");
    // Placed after link.x so it can `INSERT BEFORE` link.x's own `.data`.
    println!("cargo:rustc-link-arg=-Tgate-buf.x");
    println!("cargo:rustc-link-arg=-Map=catcard.map");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-env=CATCARD_BOARD={}", board.name);
}

fn board_from_features() -> &'static catcard_board::BoardSpec {
    // Driven off `spec::ALL` rather than a tuple match, so adding a board is one entry
    // in the spec table and a feature -- the tuple grew a dimension per board, and
    // forgetting this function gave "no board selected" for a board that exists.
    let selected: Vec<&catcard_board::BoardSpec> = catcard_board::spec::ALL
        .iter()
        .filter(|b| {
            env::var_os(format!(
                "CARGO_FEATURE_BOARD_{}",
                b.name.to_uppercase().replace('-', "_")
            ))
            .is_some()
        })
        .collect();

    match selected.as_slice() {
        [one] => one,
        [] => {
            let aliases: Vec<String> = catcard_board::spec::ALL
                .iter()
                .map(|b| format!("  cargo fw-{}", b.name))
                .collect();
            panic!(
                "no board selected. Build with one of:\n{}",
                aliases.join("\n")
            )
        }
        _ => panic!("more than one board feature is enabled; pick exactly one"),
    }
}
