#!/usr/bin/env python3
"""Convert a BDF bitmap font into a Rust module for `catcard-ui`.

Emits fixed-cell, row-major glyphs for printable ASCII. BDF stores each glyph in its
own bounding box with offsets from the baseline; this composites them into one uniform
cell so the renderer does not carry per-glyph geometry.

The vertical placement is the part worth stating: BDF's y axis grows *upward* from the
baseline, while a framebuffer's grows downward. A glyph's first row therefore sits at

    (font_bbox_yoff + font_bbox_h) - (glyph_bbox_yoff + glyph_bbox_h)

rows below the top of the cell. Getting that backwards renders text that looks correct
for symmetric glyphs and one pixel off for descenders, which is exactly the kind of
thing nobody notices until it is on a device.
"""
import sys, re

FIRST, LAST = 0x20, 0x7E


def parse_bdf(path):
    fbb = None
    glyphs = {}
    enc = bbx = None
    bits = None
    for line in open(path, encoding="latin-1"):
        line = line.rstrip("\n")
        if line.startswith("FONTBOUNDINGBOX"):
            fbb = [int(x) for x in line.split()[1:5]]
        elif line.startswith("ENCODING"):
            enc = int(line.split()[1])
        elif line.startswith("BBX"):
            bbx = [int(x) for x in line.split()[1:5]]
        elif line == "BITMAP":
            bits = []
        elif line == "ENDCHAR":
            if bits is not None and enc is not None and FIRST <= enc <= LAST:
                glyphs[enc] = (bbx, bits)
            enc = bbx = bits = None
        elif bits is not None and re.fullmatch(r"[0-9A-Fa-f]+", line):
            bits.append(line)
    return fbb, glyphs


def render(fbb, bbx, bits):
    """Composite one glyph into the font's fixed cell. Returns a list of row ints."""
    fw, fh, fx, fy = fbb
    gw, gh, gx, gy = bbx
    cell = [0] * fh
    row0 = (fy + fh) - (gy + gh)
    col0 = gx - fx
    for i, hexrow in enumerate(bits):
        r = row0 + i
        if not (0 <= r < fh):
            continue
        # BDF rows are hex, padded to whole bytes, most significant bit leftmost.
        v = int(hexrow, 16) << (0 if len(hexrow) * 4 >= gw else 0)
        width_bits = len(hexrow) * 4
        for c in range(gw):
            if v & (1 << (width_bits - 1 - c)):
                x = col0 + c
                if 0 <= x < fw:
                    cell[r] |= 1 << (fw - 1 - x)
    return cell


def main(path, modname, ident, attribution):
    fbb, glyphs = parse_bdf(path)
    fw, fh = fbb[0], fbb[1]
    bpr = (fw + 7) // 8

    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        sys.exit(f"{path}: missing glyphs {missing}")

    rows_out = []
    for c in range(FIRST, LAST + 1):
        cell = render(fbb, *glyphs[c])
        flat = []
        for r in cell:
            # Left-align the row in `bpr` bytes, most significant bit leftmost.
            shifted = r << (bpr * 8 - fw)
            flat += [(shifted >> (8 * (bpr - 1 - b))) & 0xFF for b in range(bpr)]
        rows_out.append(
            "    " + " ".join(f"0x{b:02x}," for b in flat) + f" // {chr(c)!r}"
        )

    print(f'''//! {ident} — a {fw}x{fh} bitmap face.
//!
{attribution}
//!
//! Row-major, most significant bit leftmost, {bpr} byte(s) per row, {fh} rows per glyph,
//! for printable ASCII `0x20..=0x7E`.
//!
//! Generated by `tools/fontgen/bdf2rs.py` — do not hand-edit.

use super::Font;

#[rustfmt::skip]
static GLYPHS: [u8; {(LAST - FIRST + 1) * bpr * fh}] = [
{chr(10).join(rows_out)}
];

/// The face.
pub static FONT: Font = Font {{
    width: {fw},
    height: {fh},
    bytes_per_row: {bpr},
    first: 0x{FIRST:02x},
    last: 0x{LAST:02x},
    glyphs: &GLYPHS,
}};''')


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
