#!/usr/bin/env python3
"""Bake pixel-art PNGs into indexed Rust tables sharing one palette.

    tools/artgen/pixels2rs.py ICONS/ crates/catcard-ui/src/art/menuicons.rs

The sibling `svg2rs.py` rasterises one SVG and quantises it to its own palette, which is
right for a full-screen picture and wrong for a grid: everything on one scanline is sent
through a single 16-entry palette, so icons shown side by side have to share one. This
takes a directory of already-indexed pixel art and maps the whole set onto one.

Nothing is quantised or resampled. The art is authored at the size it is shown and in the
colours it is shown in, so this is a mapping, not a conversion -- if a PNG holds a colour
the shared palette has no room for, that is an error rather than a nearest-match, because
a silently-substituted colour in a 64x64 icon is a bug nobody sees until the hardware is
in front of them.

Index layout, which the renderer depends on:

  0       the background. Fully transparent pixels map here and `draw_indexed` skips
          them, so this is the transparency -- but it still has a colour, because the
          canvas underneath is cleared to index 0 and that is what shows through. Pass
          `--background` to set it.
  1..14   the art's colours.
  15      white, which is also what text draws in (`canvas::INK`).

Needs Pillow.
"""
import argparse
import pathlib
import sys

from PIL import Image

BACKGROUND, WHITE = 0, 15
BLACK_RGB, WHITE_RGB = (0, 0, 0), (255, 255, 255)


def rgb565(c):
    r, g, b = c
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def load(path):
    """(width, height, [(r,g,b) or None]) — None where fully transparent."""
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    out = []
    for r, g, b, a in im.getdata():
        if a == 0:
            out.append(None)
        elif a != 255:
            sys.exit(
                f"{path.name}: alpha {a} at a pixel. The index format has no partial "
                f"transparency -- a pixel is drawn or it is not."
            )
        else:
            out.append((r, g, b))
    return w, h, out


def assign(colours):
    """Colour -> index. White is pinned to 15 because text draws there."""
    order = sorted(colours, key=lambda c: (c != BLACK_RGB, c))
    table = {}
    nxt = 1
    for c in order:
        if c == WHITE_RGB:
            table[c] = WHITE
            continue
        if nxt >= WHITE:
            sys.exit(
                f"more than {WHITE - 1} colours across the set; the panel sends one "
                f"16-entry palette per scanline and index 0 and {WHITE} are spoken for"
            )
        table[c] = nxt
        nxt += 1
    return table


def pack(pixels, w, table):
    """Two pixels a byte, the left one in the high nibble."""
    out = bytearray()
    for y in range(len(pixels) // w):
        row = pixels[y * w : (y + 1) * w]
        for i in range(0, w, 2):
            hi = BACKGROUND if row[i] is None else table[row[i]]
            lo = 0
            if i + 1 < w:
                lo = BACKGROUND if row[i + 1] is None else table[row[i + 1]]
            out.append((hi << 4) | lo)
    return bytes(out)


def ident(stem):
    return stem.upper().replace("-", "_").replace(" ", "_")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src", type=pathlib.Path, help="directory of 64x64 RGBA PNGs")
    ap.add_argument("out", type=pathlib.Path)
    ap.add_argument("--module", default="the menu icons")
    ap.add_argument(
        "--background",
        default="000000",
        help="RRGGBB for index 0, what shows through the art and behind the screen",
    )
    args = ap.parse_args()

    files = sorted(p for p in args.src.glob("*.png") if p.stem != "preview")
    if not files:
        sys.exit(f"no PNGs in {args.src}")

    art = {}
    colours = set()
    size = None
    for f in files:
        w, h, px = load(f)
        if size and (w, h) != size:
            sys.exit(f"{f.name} is {w}x{h}, but {size[0]}x{size[1]} was seen first")
        size = (w, h)
        art[f.stem] = (w, h, px)
        colours |= {c for c in px if c is not None}

    table = assign(colours)
    palette = [0] * 16
    for c, i in table.items():
        palette[i] = rgb565(c)
    bg = args.background.lstrip("#")
    palette[BACKGROUND] = rgb565(tuple(int(bg[i : i + 2], 16) for i in (0, 2, 4)))

    lines = [
        f"//! {args.module}: pixel art, as indices into one shared palette.",
        "//!",
        "//! Generated by `tools/artgen/pixels2rs.py` -- edit the PNGs and re-run it.",
        "//!",
        "//! One palette for the whole set, because the panel maps a scanline's indices",
        "//! through a single 16-entry table at send time and these are shown side by",
        "//! side. Index 0 is the transparent background and is not drawn; index 15 is",
        "//! white, which is what the labels draw in too.",
        "",
        "use super::indexed::Indexed;",
        "",
        f"/// The colours all {len(art)} icons are drawn from, RGB565.",
        "///",
        f"/// Index 0 is the background (#{bg.upper()}): the art leaves it alone and the",
        "/// screen behind is cleared to it, so it is what shows through.",
        "#[rustfmt::skip]",
        "pub const PALETTE: [u16; 16] = [",
        "    " + ", ".join(f"0x{v:04X}" for v in palette) + ",",
        "];",
        "",
    ]
    for stem, (w, h, px) in art.items():
        data = pack(px, w, table)
        lines += [
            f"/// `{stem}.png`, {w}x{h}.",
            "#[rustfmt::skip]",
            f"pub const {ident(stem)}: Indexed = Indexed {{",
            f"    width: {w},",
            f"    height: {h},",
            "    palette: PALETTE,",
            "    pixels: &[",
        ]
        per = 16
        for i in range(0, len(data), per):
            chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + per])
            lines.append(f"        {chunk},")
        lines += ["    ],", "};", ""]

    args.out.write_text("\n".join(lines))
    used = len([c for c in table])
    print(f"{len(art)} icons, {size[0]}x{size[1]}, {used} colours -> {args.out}")
    print(f"   0  #{bg.upper()}  (background)")
    for c, i in sorted(table.items(), key=lambda kv: kv[1]):
        print(f"  {i:2}  #{c[0]:02X}{c[1]:02X}{c[2]:02X}")


if __name__ == "__main__":
    main()
