#!/usr/bin/env python3
"""Bake an SVG into an indexed-colour Rust table for `catcard_ui::art`.

    tools/artgen/svg2rs.py ART.svg 120 crates/catcard-ui/src/art/tibane.rs --name LOGO

The panel's canvas holds 4 bits per pixel and the flush maps them through a 16-entry
RGB565 palette, so a picture travels as its own palette plus one nibble per pixel. That
is how a rasterised SVG -- glow, gradient, anti-aliased edges -- reaches the screen
without the 150 KB RGB565 framebuffer nobody has the RAM for.

What the renderer produced is what gets baked: rasterise on black at the size it will be
shown, quantise the result, and keep those pixels. Index 0 is black (the background, not
drawn) and index 15 is white (text and the progress bar), leaving 14 for the art.

Needs `rsvg-convert` (librsvg) and Pillow.
"""
import argparse, pathlib, subprocess, sys

from PIL import Image

BLACK, WHITE = 0, 15
ART_COLOURS = 14


def rgb565(c):
    r, g, b = c
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def rasterise(svg: pathlib.Path, px: int) -> Image.Image:
    """Render on black at the size it will be shown, so the glow lands on the real
    background rather than on transparency that a later composite would fake."""
    out = subprocess.run(
        ["rsvg-convert", "-w", str(px), "-h", str(px), "-b", "black", str(svg)],
        check=True, stdout=subprocess.PIPE,
    ).stdout
    tmp = pathlib.Path(f"/tmp/svg2rs-{px}.png")
    tmp.write_bytes(out)
    return Image.open(tmp).convert("RGB")


def build(img: Image.Image):
    """Quantise to the art colours, then map onto indices 1..14 with 0 black, 15 white."""
    q = img.quantize(colors=ART_COLOURS, method=Image.MEDIANCUT, dither=Image.NONE)
    pal = q.getpalette()[: ART_COLOURS * 3]
    colours = [tuple(pal[i * 3 : i * 3 + 3]) for i in range(ART_COLOURS)]

    # Whatever the quantiser called the background becomes index 0, so art over black
    # needs no transparency mask: the background simply is not drawn.
    darkest = min(range(ART_COLOURS), key=lambda i: sum(colours[i]))
    order = [darkest] + [i for i in range(ART_COLOURS) if i != darkest]
    index_of = {q_index: slot for slot, q_index in enumerate(order)}

    palette = [0] * 16
    for slot, q_index in enumerate(order):
        palette[slot] = rgb565(colours[q_index])
    palette[BLACK] = 0x0000
    palette[WHITE] = 0xFFFF

    w, h = q.size
    src = q.load()
    row_len = (w + 1) // 2
    pixels = bytearray(row_len * h)
    for y in range(h):
        for x in range(w):
            slot = index_of[src[x, y]]
            if slot >= WHITE:  # never hand art the reserved white
                slot = WHITE - 1
            at = y * row_len + x // 2
            pixels[at] |= slot << (4 if x % 2 == 0 else 0)
    return w, h, palette, bytes(pixels)


def emit(name, source, w, h, palette, pixels) -> str:
    rows = []
    row_len = (w + 1) // 2
    for y in range(h):
        row = pixels[y * row_len : (y + 1) * row_len]
        rows.append("    " + " ".join(f"0x{b:02x}," for b in row))
    pal = "\n".join(f"    {c:#06x}," for c in palette)
    return f'''//! {source.name}, rasterised and baked as indexed-colour pixels.
//!
//! Generated by `tools/artgen/svg2rs.py` from `{source.name}` beside this file -- do not
//! hand-edit. Re-run it to change the art.
//!
//! Rendered on black at {w}x{h}, the size it is shown at, so the glow and the gradient are
//! the renderer's own pixels rather than something reconstructed on the device. Quantised
//! to {ART_COLOURS} colours; index 0 is the background (not drawn) and index 15 is white,
//! left for text on the same canvas.

use super::Indexed;

#[rustfmt::skip]
static PIXELS: [u8; {len(pixels)}] = [
{chr(10).join(rows)}
];

/// The palette these pixels index, RGB565.
#[rustfmt::skip]
static PALETTE: [u16; 16] = [
{pal}
];

pub const {name}: Indexed = Indexed {{
    width: {w},
    height: {h},
    palette: PALETTE,
    pixels: &PIXELS,
}};
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("svg", type=pathlib.Path)
    ap.add_argument("size", type=int, help="pixels, square")
    ap.add_argument("out", type=pathlib.Path)
    ap.add_argument("--name", default="LOGO")
    a = ap.parse_args()

    img = rasterise(a.svg, a.size)
    w, h, palette, pixels = build(img)
    a.out.write_text(emit(a.name, a.svg, w, h, palette, pixels))
    used = len({p for p in pixels})
    print(f"{a.out}: {w}x{h}, {len(pixels)} bytes of pixels, {used} distinct packed bytes")
    print("palette:", " ".join(f"{c:#06x}" for c in palette))


if __name__ == "__main__":
    sys.exit(main())
