#!/usr/bin/env python3
"""Extract the HMAC_DRBG SHA-256 cases from NIST's CAVP DRBG vectors into the compact
file `crates/catcard-entropy/tests/data/hmac_drbg_sha256.txt`.

Source: NIST CSRC, CAVP "Random Number Generators" page, `drbgtestvectors.zip`
<https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/drbg/drbgtestvectors.zip>.
It holds three inner zips (`drbgvectors_no_reseed.zip`, `drbgvectors_pr_false.zip`,
`drbgvectors_pr_true.zip`), each with an `HMAC_DRBG.rsp`. Unpack each inner zip into a
directory named after its mode (`no_reseed/`, `pr_false/`, `pr_true/`), then:

    python3 tools/reference/cavp_hmac_drbg_extract.py <dir> \
        > crates/catcard-entropy/tests/data/hmac_drbg_sha256.txt

Output: one case per line, space-separated hex, `-` for an empty field.

    N  entropy nonce pers  add1 add2                                 returned
    R  entropy nonce pers  reseed_entropy reseed_add  add1 add2       returned
    P  entropy nonce pers  add1 entropy_pr1  add2 entropy_pr2         returned

`N` is `no_reseed`, `R` is `pr_false` (one explicit reseed between instantiate and the
two generates), `P` is `pr_true` (prediction resistance: a reseed before each generate).
The CAVP procedure generates twice and reports only the second output.
"""

import hashlib
import os
import sys

MODES = [("no_reseed", "N"), ("pr_false", "R"), ("pr_true", "P")]

FIELDS = {
    "N": ["EntropyInput", "Nonce", "PersonalizationString", "AdditionalInput",
          "AdditionalInput", "ReturnedBits"],
    "R": ["EntropyInput", "Nonce", "PersonalizationString", "EntropyInputReseed",
          "AdditionalInputReseed", "AdditionalInput", "AdditionalInput", "ReturnedBits"],
    "P": ["EntropyInput", "Nonce", "PersonalizationString", "AdditionalInput",
          "EntropyInputPR", "AdditionalInput", "EntropyInputPR", "ReturnedBits"],
}


def cases(path, tag):
    """Yield (section header, [values in file order]) for every SHA-256 case."""
    header, hash_ = [], None
    cur = None
    with open(path) as f:
        for raw in f:
            line = raw.strip()
            if line.startswith("["):
                if line.startswith("[SHA"):
                    hash_ = line
                    header = [line]
                else:
                    header.append(line)
                continue
            if hash_ != "[SHA-256]":
                continue
            if line.startswith("COUNT"):
                cur = []
                continue
            if cur is None or "=" not in line:
                continue
            key, _, val = (p.strip() for p in line.partition("="))
            cur.append((key, val))
            if key == "ReturnedBits":
                names = [k for k, _ in cur]
                if names != FIELDS[tag]:
                    sys.exit(f"{path}: unexpected field order {names}")
                yield " ".join(header), [v or "-" for _, v in cur]
                cur = None


def sha256_file(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "."
    out = ["# NIST CAVP HMAC_DRBG, SHA-256 sections only. Generated by",
           "# tools/reference/cavp_hmac_drbg_extract.py -- do not edit by hand.",
           "#"]
    outer = os.path.join(root, "drbgtestvectors.zip")
    if os.path.exists(outer):
        out.append("# drbgtestvectors.zip sha256 " + sha256_file(outer))
    body = []
    for mode, tag in MODES:
        path = os.path.join(root, mode, "HMAC_DRBG.rsp")
        out.append(f"# drbgvectors_{mode}.zip/HMAC_DRBG.rsp sha256 " + sha256_file(path))
        seen = {}
        for header, vals in cases(path, tag):
            seen[header] = seen.get(header, 0) + 1
            body.append(tag + " " + " ".join(vals))
        for header, n in seen.items():
            out.append(f"#   {tag} {n:3} cases  {header}")
    out.append("#")
    print("\n".join(out + body))


if __name__ == "__main__":
    main()
